baseURL = "https://equalfree.github.io/"
languageCode = "zh-CN"
title = "equalfree's Blog"
theme = "hyde"
disqusShortname = ""
hasCJKLanguage = true
enableEmoji = true

[permalinks]
  posts = "/:filename/"

[Menus]
  main = [
      {Name = "Archives", URL = "https://equalfree.github.io/posts/"},
      {Name = "Tags", URL = "https://equalfree.github.io/tags/"},
      {Name = "Photos", URL = "https://equalfree.github.io/photos/"}
  ]

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # description about this website
  description = "There is only one thing in the world worse than being talked about, and that is not being talked about."

[params.valine]
  enable = false
    appId = ''
    appKey = ''
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true